---
name: Term-Bash-Completion-Generator
version: 0.01.6
author:
  - 'Nadim ibn hamouda el Khemir. <nkh@cpan.org>'
abstract: Generate bash completion scripts
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::Select: 0
  Readonly: 0
  Sub::Exporter: 0
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Strict: 0
  Test::Warn: 0
  Tree::Trie: 0
provides:
  Term::Bash::Completion::Generator:
    file: lib/Term/Bash/Completion/Generator.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
